--字符串操作,字符串索引从1开始
str1="双引号可以创建字符串"
str2='单引号也可以创建字符串'
print([[123]])
--得到字符串长度
str3="1234567"
str4="123一"
print(#str3)
print(#str4)--一个汉字是三个长度
--多行打印
print("123\n23")
print([[1
2
3]])
--字符串拼接 %d拼接数字 %a拼接任何字符 %s与字符串配对
print("123"..'1234')
print(string.format("123%s321","一二三"))
--转字符串
a=true
print(tostring(a))--直接打印默认调用tostring
--字符串提供的公共方法
str5="abCD"
print(string.upper(str5))--不会更改原字符串，同C#
print(string.lower(str5))
print(str5)
print(string.reverse(str5))--翻转字符串
print(string.find(str5,"ab"))--查找字符
print(string.sub(str5,1,3))--截取字符串
print(string.rep(str5,2))--字符串重复
print(string.gsub(str5,"a","*"))--字符串修改，把第二个参数全部改为第三个参数
print(string.byte(str5,1))--把字符串中指定位置的字符转ASCII码
print(string.char(97))--把ASCII码转为对应字符